// <auto-generated />
using System;
using Concertable.Concert.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace Concertable.Concert.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ConcertDbContext))]
    [Migration("20260502170417_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("concert")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Concertable.Artist.Domain.ArtistRatingProjection", b =>
                {
                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.HasKey("ArtistId");

                    b.ToTable("ArtistRatingProjections", "artist", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Concert.Domain.ApplicationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("OpportunityId", "ArtistId")
                        .IsUnique();

                    b.ToTable("Applications", "concert");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ApplicationEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Concertable.Concert.Domain.ArtistReadModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ArtistReadModels", "concert");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.ArtistReadModelGenre", b =>
                {
                    b.Property<int>("ArtistReadModelId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("ArtistReadModelId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("ArtistReadModelGenres", "concert");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.BookingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("Bookings", "concert");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BookingEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Concertable.Concert.Domain.ConcertEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalTickets")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("VenueId");

                    b.ToTable("Concerts", "concert");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.ConcertGenreEntity", b =>
                {
                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("ConcertId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("ConcertGenres", "concert");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.ConcertImageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConcertId");

                    b.ToTable("ConcertImages", "concert");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.ConcertRatingProjection", b =>
                {
                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.HasKey("ConcertId");

                    b.ToTable("ConcertRatingProjections", "concert");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.OpportunityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.HasIndex("VenueId");

                    b.ToTable("Opportunities", "concert");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.OpportunityGenreEntity", b =>
                {
                    b.Property<int>("OpportunityId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("OpportunityId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("OpportunityGenres", "concert");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.ReviewEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Stars")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Reviews", "concert");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.TicketEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("QrCode")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("ReviewId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConcertId");

                    b.HasIndex("ReviewId");

                    b.ToTable("Tickets", "concert");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.VenueReadModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("VenueReadModels", "concert");
                });

            modelBuilder.Entity("Concertable.Shared.GenreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Venue.Domain.VenueRatingProjection", b =>
                {
                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.HasKey("VenueId");

                    b.ToTable("VenueRatingProjections", "venue", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Concert.Domain.PrepaidApplication", b =>
                {
                    b.HasBaseType("Concertable.Concert.Domain.ApplicationEntity");

                    b.Property<string>("PaymentMethodId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("PrepaidApplication");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.StandardApplication", b =>
                {
                    b.HasBaseType("Concertable.Concert.Domain.ApplicationEntity");

                    b.HasDiscriminator().HasValue("StandardApplication");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.DeferredBooking", b =>
                {
                    b.HasBaseType("Concertable.Concert.Domain.BookingEntity");

                    b.Property<string>("PaymentMethodId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("DeferredBooking");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.StandardBooking", b =>
                {
                    b.HasBaseType("Concertable.Concert.Domain.BookingEntity");

                    b.HasDiscriminator().HasValue("StandardBooking");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.ApplicationEntity", b =>
                {
                    b.HasOne("Concertable.Concert.Domain.ArtistReadModel", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Concertable.Concert.Domain.OpportunityEntity", "Opportunity")
                        .WithMany("Applications")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.ArtistReadModelGenre", b =>
                {
                    b.HasOne("Concertable.Concert.Domain.ArtistReadModel", "Artist")
                        .WithMany("Genres")
                        .HasForeignKey("ArtistReadModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Concertable.Shared.GenreEntity", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.BookingEntity", b =>
                {
                    b.HasOne("Concertable.Concert.Domain.ApplicationEntity", "Application")
                        .WithOne("Booking")
                        .HasForeignKey("Concertable.Concert.Domain.BookingEntity", "ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.ConcertEntity", b =>
                {
                    b.HasOne("Concertable.Concert.Domain.ArtistReadModel", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Concertable.Concert.Domain.BookingEntity", "Booking")
                        .WithOne("Concert")
                        .HasForeignKey("Concertable.Concert.Domain.ConcertEntity", "BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Concertable.Concert.Domain.VenueReadModel", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Booking");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.ConcertGenreEntity", b =>
                {
                    b.HasOne("Concertable.Concert.Domain.ConcertEntity", "Concert")
                        .WithMany("ConcertGenres")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Concertable.Shared.GenreEntity", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.ConcertImageEntity", b =>
                {
                    b.HasOne("Concertable.Concert.Domain.ConcertEntity", "Concert")
                        .WithMany("Images")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.OpportunityEntity", b =>
                {
                    b.HasOne("Concertable.Concert.Domain.VenueReadModel", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("Concertable.Shared.DateRange", "Period", b1 =>
                        {
                            b1.Property<int>("OpportunityEntityId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("End")
                                .HasColumnType("datetime2")
                                .HasColumnName("EndDate");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("datetime2")
                                .HasColumnName("StartDate");

                            b1.HasKey("OpportunityEntityId");

                            b1.ToTable("Opportunities", "concert");

                            b1.WithOwner()
                                .HasForeignKey("OpportunityEntityId");
                        });

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.OpportunityGenreEntity", b =>
                {
                    b.HasOne("Concertable.Shared.GenreEntity", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Concertable.Concert.Domain.OpportunityEntity", "Opportunity")
                        .WithMany("OpportunityGenres")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.ReviewEntity", b =>
                {
                    b.HasOne("Concertable.Concert.Domain.TicketEntity", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.TicketEntity", b =>
                {
                    b.HasOne("Concertable.Concert.Domain.ConcertEntity", "Concert")
                        .WithMany("Tickets")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Concertable.Concert.Domain.ReviewEntity", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId");

                    b.Navigation("Concert");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.ApplicationEntity", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.ArtistReadModel", b =>
                {
                    b.Navigation("Genres");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.BookingEntity", b =>
                {
                    b.Navigation("Concert");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.ConcertEntity", b =>
                {
                    b.Navigation("ConcertGenres");

                    b.Navigation("Images");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Concertable.Concert.Domain.OpportunityEntity", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("OpportunityGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
