// <auto-generated />
using System;
using Concertable.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace Concertable.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260416154521_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Concertable.Core.Entities.ArtistEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Concertable.Core.Entities.ArtistGenreEntity", b =>
                {
                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("ArtistId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("ArtistGenres");
                });

            modelBuilder.Entity("Concertable.Core.Entities.ConcertEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalTickets")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("Concerts");
                });

            modelBuilder.Entity("Concertable.Core.Entities.ConcertGenreEntity", b =>
                {
                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("ConcertId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("ConcertGenres");
                });

            modelBuilder.Entity("Concertable.Core.Entities.ConcertImageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConcertId");

                    b.ToTable("ConcertImages");
                });

            modelBuilder.Entity("Concertable.Core.Entities.Contracts.ContractEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Contracts");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Concertable.Core.Entities.EmailVerificationTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerificationTokens");
                });

            modelBuilder.Entity("Concertable.Core.Entities.GenreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Concertable.Core.Entities.GenrePreferenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("PreferenceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("PreferenceId");

                    b.ToTable("GenrePreferences");
                });

            modelBuilder.Entity("Concertable.Core.Entities.MessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Action")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Concertable.Core.Entities.OpportunityApplicationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("OpportunityId", "ArtistId")
                        .IsUnique();

                    b.ToTable("OpportunityApplications");
                });

            modelBuilder.Entity("Concertable.Core.Entities.OpportunityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Opportunities");
                });

            modelBuilder.Entity("Concertable.Core.Entities.OpportunityGenreEntity", b =>
                {
                    b.Property<int>("OpportunityId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("OpportunityId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("OpportunityGenres");
                });

            modelBuilder.Entity("Concertable.Core.Entities.PasswordResetTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Concertable.Core.Entities.PreferenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("RadiusKm")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("Concertable.Core.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Concertable.Core.Entities.ReviewEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Stars")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Concertable.Core.Entities.StripeEventEntity", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EventProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.ToTable("StripeEvents");
                });

            modelBuilder.Entity("Concertable.Core.Entities.TicketEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("QrCode")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConcertId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Concertable.Core.Entities.TransactionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("PaymentIntentId")
                        .IsUnique();

                    b.HasIndex("ToUserId");

                    b.ToTable("Transactions");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Concertable.Core.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<Point>("Location")
                        .HasColumnType("geography");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<int>("Role").HasValue(3);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Concertable.Core.Entities.VenueEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<string>("BannerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("Concertable.Core.Entities.VenueImageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("VenueImages");
                });

            modelBuilder.Entity("Concertable.Core.Entities.Contracts.DoorSplitContractEntity", b =>
                {
                    b.HasBaseType("Concertable.Core.Entities.Contracts.ContractEntity");

                    b.Property<decimal>("ArtistDoorPercent")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("DoorSplitContracts");
                });

            modelBuilder.Entity("Concertable.Core.Entities.Contracts.FlatFeeContractEntity", b =>
                {
                    b.HasBaseType("Concertable.Core.Entities.Contracts.ContractEntity");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("FlatFeeContracts");
                });

            modelBuilder.Entity("Concertable.Core.Entities.Contracts.VenueHireContractEntity", b =>
                {
                    b.HasBaseType("Concertable.Core.Entities.Contracts.ContractEntity");

                    b.Property<decimal>("HireFee")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("VenueHireContracts");
                });

            modelBuilder.Entity("Concertable.Core.Entities.Contracts.VersusContractEntity", b =>
                {
                    b.HasBaseType("Concertable.Core.Entities.Contracts.ContractEntity");

                    b.Property<decimal>("ArtistDoorPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Guarantee")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("VersusContracts");
                });

            modelBuilder.Entity("Concertable.Core.Entities.SettlementTransactionEntity", b =>
                {
                    b.HasBaseType("Concertable.Core.Entities.TransactionEntity");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.HasIndex("ApplicationId");

                    b.ToTable("SettlementTransactions");
                });

            modelBuilder.Entity("Concertable.Core.Entities.TicketTransactionEntity", b =>
                {
                    b.HasBaseType("Concertable.Core.Entities.TransactionEntity");

                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.HasIndex("ConcertId");

                    b.ToTable("TicketTransactions");
                });

            modelBuilder.Entity("Concertable.Core.Entities.CustomerEntity", b =>
                {
                    b.HasBaseType("Concertable.Core.Entities.UserEntity");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Concertable.Core.Entities.ManagerEntity", b =>
                {
                    b.HasBaseType("Concertable.Core.Entities.UserEntity");

                    b.Property<string>("StripeAccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                });

            modelBuilder.Entity("Concertable.Core.Entities.ArtistManagerEntity", b =>
                {
                    b.HasBaseType("Concertable.Core.Entities.ManagerEntity");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Concertable.Core.Entities.VenueManagerEntity", b =>
                {
                    b.HasBaseType("Concertable.Core.Entities.ManagerEntity");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Concertable.Core.Entities.ArtistEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.ArtistManagerEntity", "User")
                        .WithOne("Artist")
                        .HasForeignKey("Concertable.Core.Entities.ArtistEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Concertable.Core.Entities.ArtistGenreEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.ArtistEntity", "Artist")
                        .WithMany("ArtistGenres")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Concertable.Core.Entities.GenreEntity", "Genre")
                        .WithMany("ArtistGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Concertable.Core.Entities.ConcertEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.OpportunityApplicationEntity", "Application")
                        .WithOne("Concert")
                        .HasForeignKey("Concertable.Core.Entities.ConcertEntity", "ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Concertable.Core.Entities.ConcertGenreEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.ConcertEntity", "Concert")
                        .WithMany("ConcertGenres")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Concertable.Core.Entities.GenreEntity", "Genre")
                        .WithMany("ConcertGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Concertable.Core.Entities.ConcertImageEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.ConcertEntity", "Concert")
                        .WithMany("Images")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");
                });

            modelBuilder.Entity("Concertable.Core.Entities.Contracts.ContractEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.OpportunityEntity", "Opportunity")
                        .WithOne("Contract")
                        .HasForeignKey("Concertable.Core.Entities.Contracts.ContractEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("Concertable.Core.Entities.EmailVerificationTokenEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.UserEntity", "User")
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Concertable.Core.Entities.GenrePreferenceEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.GenreEntity", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Concertable.Core.Entities.PreferenceEntity", "Preference")
                        .WithMany("GenrePreferences")
                        .HasForeignKey("PreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Preference");
                });

            modelBuilder.Entity("Concertable.Core.Entities.MessageEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.UserEntity", "FromUser")
                        .WithMany("SentMessages")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Concertable.Core.Entities.UserEntity", "ToUser")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Concertable.Core.Entities.OpportunityApplicationEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.ArtistEntity", "Artist")
                        .WithMany("Applications")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Concertable.Core.Entities.OpportunityEntity", "Opportunity")
                        .WithMany("Applications")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("Concertable.Core.Entities.OpportunityEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.VenueEntity", "Venue")
                        .WithMany("Opportunities")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("Concertable.Core.ValueObjects.DateRange", "Period", b1 =>
                        {
                            b1.Property<int>("OpportunityEntityId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("End")
                                .HasColumnType("datetime2")
                                .HasColumnName("EndDate");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("datetime2")
                                .HasColumnName("StartDate");

                            b1.HasKey("OpportunityEntityId");

                            b1.ToTable("Opportunities");

                            b1.WithOwner()
                                .HasForeignKey("OpportunityEntityId");
                        });

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Concertable.Core.Entities.OpportunityGenreEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.GenreEntity", "Genre")
                        .WithMany("OpportunityGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Concertable.Core.Entities.OpportunityEntity", "Opportunity")
                        .WithMany("OpportunityGenres")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("Concertable.Core.Entities.PasswordResetTokenEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.UserEntity", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Concertable.Core.Entities.PreferenceEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.CustomerEntity", "User")
                        .WithOne("Preference")
                        .HasForeignKey("Concertable.Core.Entities.PreferenceEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Concertable.Core.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.UserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Concertable.Core.Entities.ReviewEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.TicketEntity", "Ticket")
                        .WithOne("Review")
                        .HasForeignKey("Concertable.Core.Entities.ReviewEntity", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Concertable.Core.Entities.TicketEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.ConcertEntity", "Concert")
                        .WithMany("Tickets")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Concertable.Core.Entities.CustomerEntity", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Concertable.Core.Entities.TransactionEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.UserEntity", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Concertable.Core.Entities.UserEntity", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Concertable.Core.Entities.UserEntity", b =>
                {
                    b.OwnsOne("Concertable.Core.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("County")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("County");

                            b1.Property<string>("Town")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Town");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Concertable.Core.Entities.VenueEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.VenueManagerEntity", "User")
                        .WithOne("Venue")
                        .HasForeignKey("Concertable.Core.Entities.VenueEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Concertable.Core.Entities.VenueImageEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.VenueEntity", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Concertable.Core.Entities.Contracts.DoorSplitContractEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.Contracts.ContractEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.Core.Entities.Contracts.DoorSplitContractEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.Core.Entities.Contracts.FlatFeeContractEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.Contracts.ContractEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.Core.Entities.Contracts.FlatFeeContractEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.Core.Entities.Contracts.VenueHireContractEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.Contracts.ContractEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.Core.Entities.Contracts.VenueHireContractEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.Core.Entities.Contracts.VersusContractEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.Contracts.ContractEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.Core.Entities.Contracts.VersusContractEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.Core.Entities.SettlementTransactionEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.OpportunityApplicationEntity", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Concertable.Core.Entities.TransactionEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.Core.Entities.SettlementTransactionEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Concertable.Core.Entities.TicketTransactionEntity", b =>
                {
                    b.HasOne("Concertable.Core.Entities.ConcertEntity", "Concert")
                        .WithMany()
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Concertable.Core.Entities.TransactionEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.Core.Entities.TicketTransactionEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");
                });

            modelBuilder.Entity("Concertable.Core.Entities.ArtistEntity", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("ArtistGenres");
                });

            modelBuilder.Entity("Concertable.Core.Entities.ConcertEntity", b =>
                {
                    b.Navigation("ConcertGenres");

                    b.Navigation("Images");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Concertable.Core.Entities.GenreEntity", b =>
                {
                    b.Navigation("ArtistGenres");

                    b.Navigation("ConcertGenres");

                    b.Navigation("OpportunityGenres");
                });

            modelBuilder.Entity("Concertable.Core.Entities.OpportunityApplicationEntity", b =>
                {
                    b.Navigation("Concert");
                });

            modelBuilder.Entity("Concertable.Core.Entities.OpportunityEntity", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Contract")
                        .IsRequired();

                    b.Navigation("OpportunityGenres");
                });

            modelBuilder.Entity("Concertable.Core.Entities.PreferenceEntity", b =>
                {
                    b.Navigation("GenrePreferences");
                });

            modelBuilder.Entity("Concertable.Core.Entities.TicketEntity", b =>
                {
                    b.Navigation("Review");
                });

            modelBuilder.Entity("Concertable.Core.Entities.UserEntity", b =>
                {
                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SentMessages");
                });

            modelBuilder.Entity("Concertable.Core.Entities.VenueEntity", b =>
                {
                    b.Navigation("Opportunities");
                });

            modelBuilder.Entity("Concertable.Core.Entities.CustomerEntity", b =>
                {
                    b.Navigation("Preference");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Concertable.Core.Entities.ArtistManagerEntity", b =>
                {
                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Concertable.Core.Entities.VenueManagerEntity", b =>
                {
                    b.Navigation("Venue");
                });
#pragma warning restore 612, 618
        }
    }
}
