// <auto-generated />
using Concertable.Contract.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Concertable.Contract.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ContractDbContext))]
    [Migration("20260502170433_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("contract")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Concertable.Contract.Domain.ContractEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Contracts", "contract");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Concertable.Contract.Domain.DoorSplitContractEntity", b =>
                {
                    b.HasBaseType("Concertable.Contract.Domain.ContractEntity");

                    b.Property<decimal>("ArtistDoorPercent")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("DoorSplitContracts", "contract");
                });

            modelBuilder.Entity("Concertable.Contract.Domain.FlatFeeContractEntity", b =>
                {
                    b.HasBaseType("Concertable.Contract.Domain.ContractEntity");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("FlatFeeContracts", "contract");
                });

            modelBuilder.Entity("Concertable.Contract.Domain.VenueHireContractEntity", b =>
                {
                    b.HasBaseType("Concertable.Contract.Domain.ContractEntity");

                    b.Property<decimal>("HireFee")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("VenueHireContracts", "contract");
                });

            modelBuilder.Entity("Concertable.Contract.Domain.VersusContractEntity", b =>
                {
                    b.HasBaseType("Concertable.Contract.Domain.ContractEntity");

                    b.Property<decimal>("ArtistDoorPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Guarantee")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("VersusContracts", "contract");
                });

            modelBuilder.Entity("Concertable.Contract.Domain.DoorSplitContractEntity", b =>
                {
                    b.HasOne("Concertable.Contract.Domain.ContractEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.Contract.Domain.DoorSplitContractEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.Contract.Domain.FlatFeeContractEntity", b =>
                {
                    b.HasOne("Concertable.Contract.Domain.ContractEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.Contract.Domain.FlatFeeContractEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.Contract.Domain.VenueHireContractEntity", b =>
                {
                    b.HasOne("Concertable.Contract.Domain.ContractEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.Contract.Domain.VenueHireContractEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.Contract.Domain.VersusContractEntity", b =>
                {
                    b.HasOne("Concertable.Contract.Domain.ContractEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.Contract.Domain.VersusContractEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
