/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as StripeReturnRouteImport } from './routes/stripe-return'
import { Route as StripeRefreshRouteImport } from './routes/stripe-refresh'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FailRouteImport } from './routes/fail'
import { Route as CustomerRouteRouteImport } from './routes/_customer/route'
import { Route as CustomerIndexRouteImport } from './routes/_customer/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CustomerSettingsRouteRouteImport } from './routes/_customer/settings/route'
import { Route as CustomerProfileRouteRouteImport } from './routes/_customer/profile/route'
import { Route as CustomerSettingsIndexRouteImport } from './routes/_customer/settings/index'
import { Route as CustomerProfileIndexRouteImport } from './routes/_customer/profile/index'
import { Route as CustomerFindIndexRouteImport } from './routes/_customer/find/index'
import { Route as CustomerSettingsPaymentRouteImport } from './routes/_customer/settings/payment'
import { Route as CustomerProfileLocationRouteImport } from './routes/_customer/profile/location'
import { Route as CustomerProfileTicketsIndexRouteImport } from './routes/_customer/profile/tickets/index'
import { Route as CustomerProfilePreferencesIndexRouteImport } from './routes/_customer/profile/preferences/index'
import { Route as CustomerProfileTicketsUpcomingRouteImport } from './routes/_customer/profile/tickets/upcoming'
import { Route as CustomerProfileTicketsHistoryRouteImport } from './routes/_customer/profile/tickets/history'
import { Route as CustomerProfilePreferencesCreateRouteImport } from './routes/_customer/profile/preferences/create'
import { Route as CustomerFindVenueIdRouteImport } from './routes/_customer/find/venue.$id'
import { Route as CustomerFindConcertIdRouteImport } from './routes/_customer/find/concert.$id'
import { Route as CustomerFindArtistIdRouteImport } from './routes/_customer/find/artist.$id'
import { Route as CustomerConcertCheckoutIdRouteImport } from './routes/_customer/concert/checkout.$id'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const StripeReturnRoute = StripeReturnRouteImport.update({
  id: '/stripe-return',
  path: '/stripe-return',
  getParentRoute: () => rootRouteImport,
} as any)
const StripeRefreshRoute = StripeRefreshRouteImport.update({
  id: '/stripe-refresh',
  path: '/stripe-refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FailRoute = FailRouteImport.update({
  id: '/fail',
  path: '/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRouteRoute = CustomerRouteRouteImport.update({
  id: '/_customer',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSettingsRouteRoute = CustomerSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerProfileRouteRoute = CustomerProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerSettingsIndexRoute = CustomerSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerSettingsRouteRoute,
} as any)
const CustomerProfileIndexRoute = CustomerProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerProfileRouteRoute,
} as any)
const CustomerFindIndexRoute = CustomerFindIndexRouteImport.update({
  id: '/find/',
  path: '/find/',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerSettingsPaymentRoute = CustomerSettingsPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => CustomerSettingsRouteRoute,
} as any)
const CustomerProfileLocationRoute = CustomerProfileLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => CustomerProfileRouteRoute,
} as any)
const CustomerProfileTicketsIndexRoute =
  CustomerProfileTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => CustomerProfileRouteRoute,
  } as any)
const CustomerProfilePreferencesIndexRoute =
  CustomerProfilePreferencesIndexRouteImport.update({
    id: '/preferences/',
    path: '/preferences/',
    getParentRoute: () => CustomerProfileRouteRoute,
  } as any)
const CustomerProfileTicketsUpcomingRoute =
  CustomerProfileTicketsUpcomingRouteImport.update({
    id: '/tickets/upcoming',
    path: '/tickets/upcoming',
    getParentRoute: () => CustomerProfileRouteRoute,
  } as any)
const CustomerProfileTicketsHistoryRoute =
  CustomerProfileTicketsHistoryRouteImport.update({
    id: '/tickets/history',
    path: '/tickets/history',
    getParentRoute: () => CustomerProfileRouteRoute,
  } as any)
const CustomerProfilePreferencesCreateRoute =
  CustomerProfilePreferencesCreateRouteImport.update({
    id: '/preferences/create',
    path: '/preferences/create',
    getParentRoute: () => CustomerProfileRouteRoute,
  } as any)
const CustomerFindVenueIdRoute = CustomerFindVenueIdRouteImport.update({
  id: '/find/venue/$id',
  path: '/find/venue/$id',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerFindConcertIdRoute = CustomerFindConcertIdRouteImport.update({
  id: '/find/concert/$id',
  path: '/find/concert/$id',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerFindArtistIdRoute = CustomerFindArtistIdRouteImport.update({
  id: '/find/artist/$id',
  path: '/find/artist/$id',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerConcertCheckoutIdRoute =
  CustomerConcertCheckoutIdRouteImport.update({
    id: '/concert/checkout/$id',
    path: '/concert/checkout/$id',
    getParentRoute: () => CustomerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof CustomerIndexRoute
  '/fail': typeof FailRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stripe-refresh': typeof StripeRefreshRoute
  '/stripe-return': typeof StripeReturnRoute
  '/success': typeof SuccessRoute
  '/profile': typeof CustomerProfileRouteRouteWithChildren
  '/settings': typeof CustomerSettingsRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/profile/location': typeof CustomerProfileLocationRoute
  '/settings/payment': typeof CustomerSettingsPaymentRoute
  '/find/': typeof CustomerFindIndexRoute
  '/profile/': typeof CustomerProfileIndexRoute
  '/settings/': typeof CustomerSettingsIndexRoute
  '/concert/checkout/$id': typeof CustomerConcertCheckoutIdRoute
  '/find/artist/$id': typeof CustomerFindArtistIdRoute
  '/find/concert/$id': typeof CustomerFindConcertIdRoute
  '/find/venue/$id': typeof CustomerFindVenueIdRoute
  '/profile/preferences/create': typeof CustomerProfilePreferencesCreateRoute
  '/profile/tickets/history': typeof CustomerProfileTicketsHistoryRoute
  '/profile/tickets/upcoming': typeof CustomerProfileTicketsUpcomingRoute
  '/profile/preferences/': typeof CustomerProfilePreferencesIndexRoute
  '/profile/tickets/': typeof CustomerProfileTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/fail': typeof FailRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stripe-refresh': typeof StripeRefreshRoute
  '/stripe-return': typeof StripeReturnRoute
  '/success': typeof SuccessRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof CustomerIndexRoute
  '/profile/location': typeof CustomerProfileLocationRoute
  '/settings/payment': typeof CustomerSettingsPaymentRoute
  '/find': typeof CustomerFindIndexRoute
  '/profile': typeof CustomerProfileIndexRoute
  '/settings': typeof CustomerSettingsIndexRoute
  '/concert/checkout/$id': typeof CustomerConcertCheckoutIdRoute
  '/find/artist/$id': typeof CustomerFindArtistIdRoute
  '/find/concert/$id': typeof CustomerFindConcertIdRoute
  '/find/venue/$id': typeof CustomerFindVenueIdRoute
  '/profile/preferences/create': typeof CustomerProfilePreferencesCreateRoute
  '/profile/tickets/history': typeof CustomerProfileTicketsHistoryRoute
  '/profile/tickets/upcoming': typeof CustomerProfileTicketsUpcomingRoute
  '/profile/preferences': typeof CustomerProfilePreferencesIndexRoute
  '/profile/tickets': typeof CustomerProfileTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_customer': typeof CustomerRouteRouteWithChildren
  '/fail': typeof FailRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stripe-refresh': typeof StripeRefreshRoute
  '/stripe-return': typeof StripeReturnRoute
  '/success': typeof SuccessRoute
  '/_customer/profile': typeof CustomerProfileRouteRouteWithChildren
  '/_customer/settings': typeof CustomerSettingsRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_customer/': typeof CustomerIndexRoute
  '/_customer/profile/location': typeof CustomerProfileLocationRoute
  '/_customer/settings/payment': typeof CustomerSettingsPaymentRoute
  '/_customer/find/': typeof CustomerFindIndexRoute
  '/_customer/profile/': typeof CustomerProfileIndexRoute
  '/_customer/settings/': typeof CustomerSettingsIndexRoute
  '/_customer/concert/checkout/$id': typeof CustomerConcertCheckoutIdRoute
  '/_customer/find/artist/$id': typeof CustomerFindArtistIdRoute
  '/_customer/find/concert/$id': typeof CustomerFindConcertIdRoute
  '/_customer/find/venue/$id': typeof CustomerFindVenueIdRoute
  '/_customer/profile/preferences/create': typeof CustomerProfilePreferencesCreateRoute
  '/_customer/profile/tickets/history': typeof CustomerProfileTicketsHistoryRoute
  '/_customer/profile/tickets/upcoming': typeof CustomerProfileTicketsUpcomingRoute
  '/_customer/profile/preferences/': typeof CustomerProfilePreferencesIndexRoute
  '/_customer/profile/tickets/': typeof CustomerProfileTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fail'
    | '/login'
    | '/register'
    | '/stripe-refresh'
    | '/stripe-return'
    | '/success'
    | '/profile'
    | '/settings'
    | '/auth/callback'
    | '/profile/location'
    | '/settings/payment'
    | '/find/'
    | '/profile/'
    | '/settings/'
    | '/concert/checkout/$id'
    | '/find/artist/$id'
    | '/find/concert/$id'
    | '/find/venue/$id'
    | '/profile/preferences/create'
    | '/profile/tickets/history'
    | '/profile/tickets/upcoming'
    | '/profile/preferences/'
    | '/profile/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/fail'
    | '/login'
    | '/register'
    | '/stripe-refresh'
    | '/stripe-return'
    | '/success'
    | '/auth/callback'
    | '/'
    | '/profile/location'
    | '/settings/payment'
    | '/find'
    | '/profile'
    | '/settings'
    | '/concert/checkout/$id'
    | '/find/artist/$id'
    | '/find/concert/$id'
    | '/find/venue/$id'
    | '/profile/preferences/create'
    | '/profile/tickets/history'
    | '/profile/tickets/upcoming'
    | '/profile/preferences'
    | '/profile/tickets'
  id:
    | '__root__'
    | '/_customer'
    | '/fail'
    | '/login'
    | '/register'
    | '/stripe-refresh'
    | '/stripe-return'
    | '/success'
    | '/_customer/profile'
    | '/_customer/settings'
    | '/auth/callback'
    | '/_customer/'
    | '/_customer/profile/location'
    | '/_customer/settings/payment'
    | '/_customer/find/'
    | '/_customer/profile/'
    | '/_customer/settings/'
    | '/_customer/concert/checkout/$id'
    | '/_customer/find/artist/$id'
    | '/_customer/find/concert/$id'
    | '/_customer/find/venue/$id'
    | '/_customer/profile/preferences/create'
    | '/_customer/profile/tickets/history'
    | '/_customer/profile/tickets/upcoming'
    | '/_customer/profile/preferences/'
    | '/_customer/profile/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CustomerRouteRoute: typeof CustomerRouteRouteWithChildren
  FailRoute: typeof FailRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StripeRefreshRoute: typeof StripeRefreshRoute
  StripeReturnRoute: typeof StripeReturnRoute
  SuccessRoute: typeof SuccessRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stripe-return': {
      id: '/stripe-return'
      path: '/stripe-return'
      fullPath: '/stripe-return'
      preLoaderRoute: typeof StripeReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stripe-refresh': {
      id: '/stripe-refresh'
      path: '/stripe-refresh'
      fullPath: '/stripe-refresh'
      preLoaderRoute: typeof StripeRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fail': {
      id: '/fail'
      path: '/fail'
      fullPath: '/fail'
      preLoaderRoute: typeof FailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_customer': {
      id: '/_customer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CustomerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_customer/': {
      id: '/_customer/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_customer/settings': {
      id: '/_customer/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof CustomerSettingsRouteRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/_customer/profile': {
      id: '/_customer/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof CustomerProfileRouteRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/_customer/settings/': {
      id: '/_customer/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof CustomerSettingsIndexRouteImport
      parentRoute: typeof CustomerSettingsRouteRoute
    }
    '/_customer/profile/': {
      id: '/_customer/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof CustomerProfileIndexRouteImport
      parentRoute: typeof CustomerProfileRouteRoute
    }
    '/_customer/find/': {
      id: '/_customer/find/'
      path: '/find'
      fullPath: '/find/'
      preLoaderRoute: typeof CustomerFindIndexRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/_customer/settings/payment': {
      id: '/_customer/settings/payment'
      path: '/payment'
      fullPath: '/settings/payment'
      preLoaderRoute: typeof CustomerSettingsPaymentRouteImport
      parentRoute: typeof CustomerSettingsRouteRoute
    }
    '/_customer/profile/location': {
      id: '/_customer/profile/location'
      path: '/location'
      fullPath: '/profile/location'
      preLoaderRoute: typeof CustomerProfileLocationRouteImport
      parentRoute: typeof CustomerProfileRouteRoute
    }
    '/_customer/profile/tickets/': {
      id: '/_customer/profile/tickets/'
      path: '/tickets'
      fullPath: '/profile/tickets/'
      preLoaderRoute: typeof CustomerProfileTicketsIndexRouteImport
      parentRoute: typeof CustomerProfileRouteRoute
    }
    '/_customer/profile/preferences/': {
      id: '/_customer/profile/preferences/'
      path: '/preferences'
      fullPath: '/profile/preferences/'
      preLoaderRoute: typeof CustomerProfilePreferencesIndexRouteImport
      parentRoute: typeof CustomerProfileRouteRoute
    }
    '/_customer/profile/tickets/upcoming': {
      id: '/_customer/profile/tickets/upcoming'
      path: '/tickets/upcoming'
      fullPath: '/profile/tickets/upcoming'
      preLoaderRoute: typeof CustomerProfileTicketsUpcomingRouteImport
      parentRoute: typeof CustomerProfileRouteRoute
    }
    '/_customer/profile/tickets/history': {
      id: '/_customer/profile/tickets/history'
      path: '/tickets/history'
      fullPath: '/profile/tickets/history'
      preLoaderRoute: typeof CustomerProfileTicketsHistoryRouteImport
      parentRoute: typeof CustomerProfileRouteRoute
    }
    '/_customer/profile/preferences/create': {
      id: '/_customer/profile/preferences/create'
      path: '/preferences/create'
      fullPath: '/profile/preferences/create'
      preLoaderRoute: typeof CustomerProfilePreferencesCreateRouteImport
      parentRoute: typeof CustomerProfileRouteRoute
    }
    '/_customer/find/venue/$id': {
      id: '/_customer/find/venue/$id'
      path: '/find/venue/$id'
      fullPath: '/find/venue/$id'
      preLoaderRoute: typeof CustomerFindVenueIdRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/_customer/find/concert/$id': {
      id: '/_customer/find/concert/$id'
      path: '/find/concert/$id'
      fullPath: '/find/concert/$id'
      preLoaderRoute: typeof CustomerFindConcertIdRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/_customer/find/artist/$id': {
      id: '/_customer/find/artist/$id'
      path: '/find/artist/$id'
      fullPath: '/find/artist/$id'
      preLoaderRoute: typeof CustomerFindArtistIdRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/_customer/concert/checkout/$id': {
      id: '/_customer/concert/checkout/$id'
      path: '/concert/checkout/$id'
      fullPath: '/concert/checkout/$id'
      preLoaderRoute: typeof CustomerConcertCheckoutIdRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
  }
}

interface CustomerProfileRouteRouteChildren {
  CustomerProfileLocationRoute: typeof CustomerProfileLocationRoute
  CustomerProfileIndexRoute: typeof CustomerProfileIndexRoute
  CustomerProfilePreferencesCreateRoute: typeof CustomerProfilePreferencesCreateRoute
  CustomerProfileTicketsHistoryRoute: typeof CustomerProfileTicketsHistoryRoute
  CustomerProfileTicketsUpcomingRoute: typeof CustomerProfileTicketsUpcomingRoute
  CustomerProfilePreferencesIndexRoute: typeof CustomerProfilePreferencesIndexRoute
  CustomerProfileTicketsIndexRoute: typeof CustomerProfileTicketsIndexRoute
}

const CustomerProfileRouteRouteChildren: CustomerProfileRouteRouteChildren = {
  CustomerProfileLocationRoute: CustomerProfileLocationRoute,
  CustomerProfileIndexRoute: CustomerProfileIndexRoute,
  CustomerProfilePreferencesCreateRoute: CustomerProfilePreferencesCreateRoute,
  CustomerProfileTicketsHistoryRoute: CustomerProfileTicketsHistoryRoute,
  CustomerProfileTicketsUpcomingRoute: CustomerProfileTicketsUpcomingRoute,
  CustomerProfilePreferencesIndexRoute: CustomerProfilePreferencesIndexRoute,
  CustomerProfileTicketsIndexRoute: CustomerProfileTicketsIndexRoute,
}

const CustomerProfileRouteRouteWithChildren =
  CustomerProfileRouteRoute._addFileChildren(CustomerProfileRouteRouteChildren)

interface CustomerSettingsRouteRouteChildren {
  CustomerSettingsPaymentRoute: typeof CustomerSettingsPaymentRoute
  CustomerSettingsIndexRoute: typeof CustomerSettingsIndexRoute
}

const CustomerSettingsRouteRouteChildren: CustomerSettingsRouteRouteChildren = {
  CustomerSettingsPaymentRoute: CustomerSettingsPaymentRoute,
  CustomerSettingsIndexRoute: CustomerSettingsIndexRoute,
}

const CustomerSettingsRouteRouteWithChildren =
  CustomerSettingsRouteRoute._addFileChildren(
    CustomerSettingsRouteRouteChildren,
  )

interface CustomerRouteRouteChildren {
  CustomerProfileRouteRoute: typeof CustomerProfileRouteRouteWithChildren
  CustomerSettingsRouteRoute: typeof CustomerSettingsRouteRouteWithChildren
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerFindIndexRoute: typeof CustomerFindIndexRoute
  CustomerConcertCheckoutIdRoute: typeof CustomerConcertCheckoutIdRoute
  CustomerFindArtistIdRoute: typeof CustomerFindArtistIdRoute
  CustomerFindConcertIdRoute: typeof CustomerFindConcertIdRoute
  CustomerFindVenueIdRoute: typeof CustomerFindVenueIdRoute
}

const CustomerRouteRouteChildren: CustomerRouteRouteChildren = {
  CustomerProfileRouteRoute: CustomerProfileRouteRouteWithChildren,
  CustomerSettingsRouteRoute: CustomerSettingsRouteRouteWithChildren,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerFindIndexRoute: CustomerFindIndexRoute,
  CustomerConcertCheckoutIdRoute: CustomerConcertCheckoutIdRoute,
  CustomerFindArtistIdRoute: CustomerFindArtistIdRoute,
  CustomerFindConcertIdRoute: CustomerFindConcertIdRoute,
  CustomerFindVenueIdRoute: CustomerFindVenueIdRoute,
}

const CustomerRouteRouteWithChildren = CustomerRouteRoute._addFileChildren(
  CustomerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  CustomerRouteRoute: CustomerRouteRouteWithChildren,
  FailRoute: FailRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StripeRefreshRoute: StripeRefreshRoute,
  StripeReturnRoute: StripeReturnRoute,
  SuccessRoute: SuccessRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
