global using Concertable.Shared;
global using Concertable.Shared.Infrastructure;
global using Concertable.Search.Domain.Models;
global using Concertable.Search.Contracts;
global using Concertable.Search.Application.Interfaces;
global using Concertable.Search.Infrastructure.Mappers;
global using Concertable.Authorization.Contracts;
global using Concertable.User.Contracts;
global using Concertable.Concert.Domain;
