/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as StripeReturnRouteImport } from './routes/stripe-return'
import { Route as StripeRefreshRouteImport } from './routes/stripe-refresh'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FailRouteImport } from './routes/fail'
import { Route as VenueRouteRouteImport } from './routes/_venue/route'
import { Route as VenueIndexRouteImport } from './routes/_venue/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as VenueCreateRouteImport } from './routes/_venue/create'
import { Route as VenueMyIndexRouteImport } from './routes/_venue/my/index'
import { Route as VenueFindIndexRouteImport } from './routes/_venue/find/index'
import { Route as VenueAcceptApplicationIdRouteImport } from './routes/_venue/accept/$applicationId'
import { Route as VenueMyApplicationsIdRouteImport } from './routes/_venue/my/applications.$id'
import { Route as VenueFindArtistIdRouteImport } from './routes/_venue/find/artist.$id'
import { Route as VenueApplicationCheckoutApplicationIdRouteImport } from './routes/_venue/application/checkout.$applicationId'
import { Route as VenueMyConcertsConcertIdRouteImport } from './routes/_venue/my/concerts/concert.$id'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const StripeReturnRoute = StripeReturnRouteImport.update({
  id: '/stripe-return',
  path: '/stripe-return',
  getParentRoute: () => rootRouteImport,
} as any)
const StripeRefreshRoute = StripeRefreshRouteImport.update({
  id: '/stripe-refresh',
  path: '/stripe-refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FailRoute = FailRouteImport.update({
  id: '/fail',
  path: '/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueRouteRoute = VenueRouteRouteImport.update({
  id: '/_venue',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueIndexRoute = VenueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VenueRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueCreateRoute = VenueCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => VenueRouteRoute,
} as any)
const VenueMyIndexRoute = VenueMyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => VenueRouteRoute,
} as any)
const VenueFindIndexRoute = VenueFindIndexRouteImport.update({
  id: '/find/',
  path: '/find/',
  getParentRoute: () => VenueRouteRoute,
} as any)
const VenueAcceptApplicationIdRoute =
  VenueAcceptApplicationIdRouteImport.update({
    id: '/accept/$applicationId',
    path: '/accept/$applicationId',
    getParentRoute: () => VenueRouteRoute,
  } as any)
const VenueMyApplicationsIdRoute = VenueMyApplicationsIdRouteImport.update({
  id: '/my/applications/$id',
  path: '/my/applications/$id',
  getParentRoute: () => VenueRouteRoute,
} as any)
const VenueFindArtistIdRoute = VenueFindArtistIdRouteImport.update({
  id: '/find/artist/$id',
  path: '/find/artist/$id',
  getParentRoute: () => VenueRouteRoute,
} as any)
const VenueApplicationCheckoutApplicationIdRoute =
  VenueApplicationCheckoutApplicationIdRouteImport.update({
    id: '/application/checkout/$applicationId',
    path: '/application/checkout/$applicationId',
    getParentRoute: () => VenueRouteRoute,
  } as any)
const VenueMyConcertsConcertIdRoute =
  VenueMyConcertsConcertIdRouteImport.update({
    id: '/my/concerts/concert/$id',
    path: '/my/concerts/concert/$id',
    getParentRoute: () => VenueRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof VenueIndexRoute
  '/fail': typeof FailRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stripe-refresh': typeof StripeRefreshRoute
  '/stripe-return': typeof StripeReturnRoute
  '/success': typeof SuccessRoute
  '/create': typeof VenueCreateRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/accept/$applicationId': typeof VenueAcceptApplicationIdRoute
  '/find/': typeof VenueFindIndexRoute
  '/my/': typeof VenueMyIndexRoute
  '/application/checkout/$applicationId': typeof VenueApplicationCheckoutApplicationIdRoute
  '/find/artist/$id': typeof VenueFindArtistIdRoute
  '/my/applications/$id': typeof VenueMyApplicationsIdRoute
  '/my/concerts/concert/$id': typeof VenueMyConcertsConcertIdRoute
}
export interface FileRoutesByTo {
  '/fail': typeof FailRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stripe-refresh': typeof StripeRefreshRoute
  '/stripe-return': typeof StripeReturnRoute
  '/success': typeof SuccessRoute
  '/create': typeof VenueCreateRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof VenueIndexRoute
  '/accept/$applicationId': typeof VenueAcceptApplicationIdRoute
  '/find': typeof VenueFindIndexRoute
  '/my': typeof VenueMyIndexRoute
  '/application/checkout/$applicationId': typeof VenueApplicationCheckoutApplicationIdRoute
  '/find/artist/$id': typeof VenueFindArtistIdRoute
  '/my/applications/$id': typeof VenueMyApplicationsIdRoute
  '/my/concerts/concert/$id': typeof VenueMyConcertsConcertIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_venue': typeof VenueRouteRouteWithChildren
  '/fail': typeof FailRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stripe-refresh': typeof StripeRefreshRoute
  '/stripe-return': typeof StripeReturnRoute
  '/success': typeof SuccessRoute
  '/_venue/create': typeof VenueCreateRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_venue/': typeof VenueIndexRoute
  '/_venue/accept/$applicationId': typeof VenueAcceptApplicationIdRoute
  '/_venue/find/': typeof VenueFindIndexRoute
  '/_venue/my/': typeof VenueMyIndexRoute
  '/_venue/application/checkout/$applicationId': typeof VenueApplicationCheckoutApplicationIdRoute
  '/_venue/find/artist/$id': typeof VenueFindArtistIdRoute
  '/_venue/my/applications/$id': typeof VenueMyApplicationsIdRoute
  '/_venue/my/concerts/concert/$id': typeof VenueMyConcertsConcertIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fail'
    | '/login'
    | '/register'
    | '/stripe-refresh'
    | '/stripe-return'
    | '/success'
    | '/create'
    | '/auth/callback'
    | '/accept/$applicationId'
    | '/find/'
    | '/my/'
    | '/application/checkout/$applicationId'
    | '/find/artist/$id'
    | '/my/applications/$id'
    | '/my/concerts/concert/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/fail'
    | '/login'
    | '/register'
    | '/stripe-refresh'
    | '/stripe-return'
    | '/success'
    | '/create'
    | '/auth/callback'
    | '/'
    | '/accept/$applicationId'
    | '/find'
    | '/my'
    | '/application/checkout/$applicationId'
    | '/find/artist/$id'
    | '/my/applications/$id'
    | '/my/concerts/concert/$id'
  id:
    | '__root__'
    | '/_venue'
    | '/fail'
    | '/login'
    | '/register'
    | '/stripe-refresh'
    | '/stripe-return'
    | '/success'
    | '/_venue/create'
    | '/auth/callback'
    | '/_venue/'
    | '/_venue/accept/$applicationId'
    | '/_venue/find/'
    | '/_venue/my/'
    | '/_venue/application/checkout/$applicationId'
    | '/_venue/find/artist/$id'
    | '/_venue/my/applications/$id'
    | '/_venue/my/concerts/concert/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  VenueRouteRoute: typeof VenueRouteRouteWithChildren
  FailRoute: typeof FailRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StripeRefreshRoute: typeof StripeRefreshRoute
  StripeReturnRoute: typeof StripeReturnRoute
  SuccessRoute: typeof SuccessRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stripe-return': {
      id: '/stripe-return'
      path: '/stripe-return'
      fullPath: '/stripe-return'
      preLoaderRoute: typeof StripeReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stripe-refresh': {
      id: '/stripe-refresh'
      path: '/stripe-refresh'
      fullPath: '/stripe-refresh'
      preLoaderRoute: typeof StripeRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fail': {
      id: '/fail'
      path: '/fail'
      fullPath: '/fail'
      preLoaderRoute: typeof FailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_venue': {
      id: '/_venue'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof VenueRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_venue/': {
      id: '/_venue/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof VenueIndexRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_venue/create': {
      id: '/_venue/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof VenueCreateRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/_venue/my/': {
      id: '/_venue/my/'
      path: '/my'
      fullPath: '/my/'
      preLoaderRoute: typeof VenueMyIndexRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/_venue/find/': {
      id: '/_venue/find/'
      path: '/find'
      fullPath: '/find/'
      preLoaderRoute: typeof VenueFindIndexRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/_venue/accept/$applicationId': {
      id: '/_venue/accept/$applicationId'
      path: '/accept/$applicationId'
      fullPath: '/accept/$applicationId'
      preLoaderRoute: typeof VenueAcceptApplicationIdRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/_venue/my/applications/$id': {
      id: '/_venue/my/applications/$id'
      path: '/my/applications/$id'
      fullPath: '/my/applications/$id'
      preLoaderRoute: typeof VenueMyApplicationsIdRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/_venue/find/artist/$id': {
      id: '/_venue/find/artist/$id'
      path: '/find/artist/$id'
      fullPath: '/find/artist/$id'
      preLoaderRoute: typeof VenueFindArtistIdRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/_venue/application/checkout/$applicationId': {
      id: '/_venue/application/checkout/$applicationId'
      path: '/application/checkout/$applicationId'
      fullPath: '/application/checkout/$applicationId'
      preLoaderRoute: typeof VenueApplicationCheckoutApplicationIdRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/_venue/my/concerts/concert/$id': {
      id: '/_venue/my/concerts/concert/$id'
      path: '/my/concerts/concert/$id'
      fullPath: '/my/concerts/concert/$id'
      preLoaderRoute: typeof VenueMyConcertsConcertIdRouteImport
      parentRoute: typeof VenueRouteRoute
    }
  }
}

interface VenueRouteRouteChildren {
  VenueCreateRoute: typeof VenueCreateRoute
  VenueIndexRoute: typeof VenueIndexRoute
  VenueAcceptApplicationIdRoute: typeof VenueAcceptApplicationIdRoute
  VenueFindIndexRoute: typeof VenueFindIndexRoute
  VenueMyIndexRoute: typeof VenueMyIndexRoute
  VenueApplicationCheckoutApplicationIdRoute: typeof VenueApplicationCheckoutApplicationIdRoute
  VenueFindArtistIdRoute: typeof VenueFindArtistIdRoute
  VenueMyApplicationsIdRoute: typeof VenueMyApplicationsIdRoute
  VenueMyConcertsConcertIdRoute: typeof VenueMyConcertsConcertIdRoute
}

const VenueRouteRouteChildren: VenueRouteRouteChildren = {
  VenueCreateRoute: VenueCreateRoute,
  VenueIndexRoute: VenueIndexRoute,
  VenueAcceptApplicationIdRoute: VenueAcceptApplicationIdRoute,
  VenueFindIndexRoute: VenueFindIndexRoute,
  VenueMyIndexRoute: VenueMyIndexRoute,
  VenueApplicationCheckoutApplicationIdRoute:
    VenueApplicationCheckoutApplicationIdRoute,
  VenueFindArtistIdRoute: VenueFindArtistIdRoute,
  VenueMyApplicationsIdRoute: VenueMyApplicationsIdRoute,
  VenueMyConcertsConcertIdRoute: VenueMyConcertsConcertIdRoute,
}

const VenueRouteRouteWithChildren = VenueRouteRoute._addFileChildren(
  VenueRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  VenueRouteRoute: VenueRouteRouteWithChildren,
  FailRoute: FailRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StripeRefreshRoute: StripeRefreshRoute,
  StripeReturnRoute: StripeReturnRoute,
  SuccessRoute: SuccessRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
