/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as StripeReturnRouteImport } from './routes/stripe-return'
import { Route as StripeRefreshRouteImport } from './routes/stripe-refresh'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FailRouteImport } from './routes/fail'
import { Route as VenueRouteRouteImport } from './routes/venue/route'
import { Route as ArtistRouteRouteImport } from './routes/artist/route'
import { Route as CustomerRouteRouteImport } from './routes/_customer/route'
import { Route as VenueIndexRouteImport } from './routes/venue/index'
import { Route as ArtistIndexRouteImport } from './routes/artist/index'
import { Route as CustomerIndexRouteImport } from './routes/_customer/index'
import { Route as VenueCreateRouteImport } from './routes/venue/create'
import { Route as ArtistCreateRouteImport } from './routes/artist/create'
import { Route as CustomerSettingsRouteRouteImport } from './routes/_customer/settings/route'
import { Route as VenueMyIndexRouteImport } from './routes/venue/my/index'
import { Route as VenueFindIndexRouteImport } from './routes/venue/find/index'
import { Route as ArtistMyIndexRouteImport } from './routes/artist/my/index'
import { Route as ArtistFindIndexRouteImport } from './routes/artist/find/index'
import { Route as CustomerSettingsIndexRouteImport } from './routes/_customer/settings/index'
import { Route as CustomerFindIndexRouteImport } from './routes/_customer/find/index'
import { Route as VenueAcceptApplicationIdRouteImport } from './routes/venue/accept/$applicationId'
import { Route as CustomerSettingsPaymentRouteImport } from './routes/_customer/settings/payment'
import { Route as CustomerSettingsMyRouteImport } from './routes/_customer/settings/my'
import { Route as CustomerSettingsLocationRouteImport } from './routes/_customer/settings/location'
import { Route as CustomerSettingsTicketsIndexRouteImport } from './routes/_customer/settings/tickets/index'
import { Route as CustomerSettingsPreferencesIndexRouteImport } from './routes/_customer/settings/preferences/index'
import { Route as VenueMyApplicationsIdRouteImport } from './routes/venue/my/applications.$id'
import { Route as VenueFindArtistIdRouteImport } from './routes/venue/find/artist.$id'
import { Route as ArtistFindVenueIdRouteImport } from './routes/artist/find/venue.$id'
import { Route as CustomerSettingsTicketsUpcomingRouteImport } from './routes/_customer/settings/tickets/upcoming'
import { Route as CustomerSettingsTicketsHistoryRouteImport } from './routes/_customer/settings/tickets/history'
import { Route as CustomerSettingsPreferencesCreateRouteImport } from './routes/_customer/settings/preferences/create'
import { Route as CustomerFindVenueIdRouteImport } from './routes/_customer/find/venue.$id'
import { Route as CustomerFindConcertIdRouteImport } from './routes/_customer/find/concert.$id'
import { Route as CustomerFindArtistIdRouteImport } from './routes/_customer/find/artist.$id'
import { Route as CustomerConcertCheckoutIdRouteImport } from './routes/_customer/concert/checkout.$id'
import { Route as CustomerApplicationCheckoutIdRouteImport } from './routes/_customer/application/checkout.$id'
import { Route as VenueMyConcertsConcertIdRouteImport } from './routes/venue/my/concerts/concert.$id'
import { Route as ArtistMyConcertsConcertIdRouteImport } from './routes/artist/my/concerts/concert.$id'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const StripeReturnRoute = StripeReturnRouteImport.update({
  id: '/stripe-return',
  path: '/stripe-return',
  getParentRoute: () => rootRouteImport,
} as any)
const StripeRefreshRoute = StripeRefreshRouteImport.update({
  id: '/stripe-refresh',
  path: '/stripe-refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FailRoute = FailRouteImport.update({
  id: '/fail',
  path: '/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueRouteRoute = VenueRouteRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistRouteRoute = ArtistRouteRouteImport.update({
  id: '/artist',
  path: '/artist',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRouteRoute = CustomerRouteRouteImport.update({
  id: '/_customer',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueIndexRoute = VenueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VenueRouteRoute,
} as any)
const ArtistIndexRoute = ArtistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistRouteRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const VenueCreateRoute = VenueCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => VenueRouteRoute,
} as any)
const ArtistCreateRoute = ArtistCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ArtistRouteRoute,
} as any)
const CustomerSettingsRouteRoute = CustomerSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const VenueMyIndexRoute = VenueMyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => VenueRouteRoute,
} as any)
const VenueFindIndexRoute = VenueFindIndexRouteImport.update({
  id: '/find/',
  path: '/find/',
  getParentRoute: () => VenueRouteRoute,
} as any)
const ArtistMyIndexRoute = ArtistMyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => ArtistRouteRoute,
} as any)
const ArtistFindIndexRoute = ArtistFindIndexRouteImport.update({
  id: '/find/',
  path: '/find/',
  getParentRoute: () => ArtistRouteRoute,
} as any)
const CustomerSettingsIndexRoute = CustomerSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerSettingsRouteRoute,
} as any)
const CustomerFindIndexRoute = CustomerFindIndexRouteImport.update({
  id: '/find/',
  path: '/find/',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const VenueAcceptApplicationIdRoute =
  VenueAcceptApplicationIdRouteImport.update({
    id: '/accept/$applicationId',
    path: '/accept/$applicationId',
    getParentRoute: () => VenueRouteRoute,
  } as any)
const CustomerSettingsPaymentRoute = CustomerSettingsPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => CustomerSettingsRouteRoute,
} as any)
const CustomerSettingsMyRoute = CustomerSettingsMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => CustomerSettingsRouteRoute,
} as any)
const CustomerSettingsLocationRoute =
  CustomerSettingsLocationRouteImport.update({
    id: '/location',
    path: '/location',
    getParentRoute: () => CustomerSettingsRouteRoute,
  } as any)
const CustomerSettingsTicketsIndexRoute =
  CustomerSettingsTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => CustomerSettingsRouteRoute,
  } as any)
const CustomerSettingsPreferencesIndexRoute =
  CustomerSettingsPreferencesIndexRouteImport.update({
    id: '/preferences/',
    path: '/preferences/',
    getParentRoute: () => CustomerSettingsRouteRoute,
  } as any)
const VenueMyApplicationsIdRoute = VenueMyApplicationsIdRouteImport.update({
  id: '/my/applications/$id',
  path: '/my/applications/$id',
  getParentRoute: () => VenueRouteRoute,
} as any)
const VenueFindArtistIdRoute = VenueFindArtistIdRouteImport.update({
  id: '/find/artist/$id',
  path: '/find/artist/$id',
  getParentRoute: () => VenueRouteRoute,
} as any)
const ArtistFindVenueIdRoute = ArtistFindVenueIdRouteImport.update({
  id: '/find/venue/$id',
  path: '/find/venue/$id',
  getParentRoute: () => ArtistRouteRoute,
} as any)
const CustomerSettingsTicketsUpcomingRoute =
  CustomerSettingsTicketsUpcomingRouteImport.update({
    id: '/tickets/upcoming',
    path: '/tickets/upcoming',
    getParentRoute: () => CustomerSettingsRouteRoute,
  } as any)
const CustomerSettingsTicketsHistoryRoute =
  CustomerSettingsTicketsHistoryRouteImport.update({
    id: '/tickets/history',
    path: '/tickets/history',
    getParentRoute: () => CustomerSettingsRouteRoute,
  } as any)
const CustomerSettingsPreferencesCreateRoute =
  CustomerSettingsPreferencesCreateRouteImport.update({
    id: '/preferences/create',
    path: '/preferences/create',
    getParentRoute: () => CustomerSettingsRouteRoute,
  } as any)
const CustomerFindVenueIdRoute = CustomerFindVenueIdRouteImport.update({
  id: '/find/venue/$id',
  path: '/find/venue/$id',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerFindConcertIdRoute = CustomerFindConcertIdRouteImport.update({
  id: '/find/concert/$id',
  path: '/find/concert/$id',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerFindArtistIdRoute = CustomerFindArtistIdRouteImport.update({
  id: '/find/artist/$id',
  path: '/find/artist/$id',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerConcertCheckoutIdRoute =
  CustomerConcertCheckoutIdRouteImport.update({
    id: '/concert/checkout/$id',
    path: '/concert/checkout/$id',
    getParentRoute: () => CustomerRouteRoute,
  } as any)
const CustomerApplicationCheckoutIdRoute =
  CustomerApplicationCheckoutIdRouteImport.update({
    id: '/application/checkout/$id',
    path: '/application/checkout/$id',
    getParentRoute: () => CustomerRouteRoute,
  } as any)
const VenueMyConcertsConcertIdRoute =
  VenueMyConcertsConcertIdRouteImport.update({
    id: '/my/concerts/concert/$id',
    path: '/my/concerts/concert/$id',
    getParentRoute: () => VenueRouteRoute,
  } as any)
const ArtistMyConcertsConcertIdRoute =
  ArtistMyConcertsConcertIdRouteImport.update({
    id: '/my/concerts/concert/$id',
    path: '/my/concerts/concert/$id',
    getParentRoute: () => ArtistRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof CustomerIndexRoute
  '/artist': typeof ArtistRouteRouteWithChildren
  '/venue': typeof VenueRouteRouteWithChildren
  '/fail': typeof FailRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stripe-refresh': typeof StripeRefreshRoute
  '/stripe-return': typeof StripeReturnRoute
  '/success': typeof SuccessRoute
  '/settings': typeof CustomerSettingsRouteRouteWithChildren
  '/artist/create': typeof ArtistCreateRoute
  '/venue/create': typeof VenueCreateRoute
  '/artist/': typeof ArtistIndexRoute
  '/venue/': typeof VenueIndexRoute
  '/settings/location': typeof CustomerSettingsLocationRoute
  '/settings/my': typeof CustomerSettingsMyRoute
  '/settings/payment': typeof CustomerSettingsPaymentRoute
  '/venue/accept/$applicationId': typeof VenueAcceptApplicationIdRoute
  '/find/': typeof CustomerFindIndexRoute
  '/settings/': typeof CustomerSettingsIndexRoute
  '/artist/find/': typeof ArtistFindIndexRoute
  '/artist/my/': typeof ArtistMyIndexRoute
  '/venue/find/': typeof VenueFindIndexRoute
  '/venue/my/': typeof VenueMyIndexRoute
  '/application/checkout/$id': typeof CustomerApplicationCheckoutIdRoute
  '/concert/checkout/$id': typeof CustomerConcertCheckoutIdRoute
  '/find/artist/$id': typeof CustomerFindArtistIdRoute
  '/find/concert/$id': typeof CustomerFindConcertIdRoute
  '/find/venue/$id': typeof CustomerFindVenueIdRoute
  '/settings/preferences/create': typeof CustomerSettingsPreferencesCreateRoute
  '/settings/tickets/history': typeof CustomerSettingsTicketsHistoryRoute
  '/settings/tickets/upcoming': typeof CustomerSettingsTicketsUpcomingRoute
  '/artist/find/venue/$id': typeof ArtistFindVenueIdRoute
  '/venue/find/artist/$id': typeof VenueFindArtistIdRoute
  '/venue/my/applications/$id': typeof VenueMyApplicationsIdRoute
  '/settings/preferences/': typeof CustomerSettingsPreferencesIndexRoute
  '/settings/tickets/': typeof CustomerSettingsTicketsIndexRoute
  '/artist/my/concerts/concert/$id': typeof ArtistMyConcertsConcertIdRoute
  '/venue/my/concerts/concert/$id': typeof VenueMyConcertsConcertIdRoute
}
export interface FileRoutesByTo {
  '/fail': typeof FailRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stripe-refresh': typeof StripeRefreshRoute
  '/stripe-return': typeof StripeReturnRoute
  '/success': typeof SuccessRoute
  '/artist/create': typeof ArtistCreateRoute
  '/venue/create': typeof VenueCreateRoute
  '/': typeof CustomerIndexRoute
  '/artist': typeof ArtistIndexRoute
  '/venue': typeof VenueIndexRoute
  '/settings/location': typeof CustomerSettingsLocationRoute
  '/settings/my': typeof CustomerSettingsMyRoute
  '/settings/payment': typeof CustomerSettingsPaymentRoute
  '/venue/accept/$applicationId': typeof VenueAcceptApplicationIdRoute
  '/find': typeof CustomerFindIndexRoute
  '/settings': typeof CustomerSettingsIndexRoute
  '/artist/find': typeof ArtistFindIndexRoute
  '/artist/my': typeof ArtistMyIndexRoute
  '/venue/find': typeof VenueFindIndexRoute
  '/venue/my': typeof VenueMyIndexRoute
  '/application/checkout/$id': typeof CustomerApplicationCheckoutIdRoute
  '/concert/checkout/$id': typeof CustomerConcertCheckoutIdRoute
  '/find/artist/$id': typeof CustomerFindArtistIdRoute
  '/find/concert/$id': typeof CustomerFindConcertIdRoute
  '/find/venue/$id': typeof CustomerFindVenueIdRoute
  '/settings/preferences/create': typeof CustomerSettingsPreferencesCreateRoute
  '/settings/tickets/history': typeof CustomerSettingsTicketsHistoryRoute
  '/settings/tickets/upcoming': typeof CustomerSettingsTicketsUpcomingRoute
  '/artist/find/venue/$id': typeof ArtistFindVenueIdRoute
  '/venue/find/artist/$id': typeof VenueFindArtistIdRoute
  '/venue/my/applications/$id': typeof VenueMyApplicationsIdRoute
  '/settings/preferences': typeof CustomerSettingsPreferencesIndexRoute
  '/settings/tickets': typeof CustomerSettingsTicketsIndexRoute
  '/artist/my/concerts/concert/$id': typeof ArtistMyConcertsConcertIdRoute
  '/venue/my/concerts/concert/$id': typeof VenueMyConcertsConcertIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_customer': typeof CustomerRouteRouteWithChildren
  '/artist': typeof ArtistRouteRouteWithChildren
  '/venue': typeof VenueRouteRouteWithChildren
  '/fail': typeof FailRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stripe-refresh': typeof StripeRefreshRoute
  '/stripe-return': typeof StripeReturnRoute
  '/success': typeof SuccessRoute
  '/_customer/settings': typeof CustomerSettingsRouteRouteWithChildren
  '/artist/create': typeof ArtistCreateRoute
  '/venue/create': typeof VenueCreateRoute
  '/_customer/': typeof CustomerIndexRoute
  '/artist/': typeof ArtistIndexRoute
  '/venue/': typeof VenueIndexRoute
  '/_customer/settings/location': typeof CustomerSettingsLocationRoute
  '/_customer/settings/my': typeof CustomerSettingsMyRoute
  '/_customer/settings/payment': typeof CustomerSettingsPaymentRoute
  '/venue/accept/$applicationId': typeof VenueAcceptApplicationIdRoute
  '/_customer/find/': typeof CustomerFindIndexRoute
  '/_customer/settings/': typeof CustomerSettingsIndexRoute
  '/artist/find/': typeof ArtistFindIndexRoute
  '/artist/my/': typeof ArtistMyIndexRoute
  '/venue/find/': typeof VenueFindIndexRoute
  '/venue/my/': typeof VenueMyIndexRoute
  '/_customer/application/checkout/$id': typeof CustomerApplicationCheckoutIdRoute
  '/_customer/concert/checkout/$id': typeof CustomerConcertCheckoutIdRoute
  '/_customer/find/artist/$id': typeof CustomerFindArtistIdRoute
  '/_customer/find/concert/$id': typeof CustomerFindConcertIdRoute
  '/_customer/find/venue/$id': typeof CustomerFindVenueIdRoute
  '/_customer/settings/preferences/create': typeof CustomerSettingsPreferencesCreateRoute
  '/_customer/settings/tickets/history': typeof CustomerSettingsTicketsHistoryRoute
  '/_customer/settings/tickets/upcoming': typeof CustomerSettingsTicketsUpcomingRoute
  '/artist/find/venue/$id': typeof ArtistFindVenueIdRoute
  '/venue/find/artist/$id': typeof VenueFindArtistIdRoute
  '/venue/my/applications/$id': typeof VenueMyApplicationsIdRoute
  '/_customer/settings/preferences/': typeof CustomerSettingsPreferencesIndexRoute
  '/_customer/settings/tickets/': typeof CustomerSettingsTicketsIndexRoute
  '/artist/my/concerts/concert/$id': typeof ArtistMyConcertsConcertIdRoute
  '/venue/my/concerts/concert/$id': typeof VenueMyConcertsConcertIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artist'
    | '/venue'
    | '/fail'
    | '/login'
    | '/register'
    | '/stripe-refresh'
    | '/stripe-return'
    | '/success'
    | '/settings'
    | '/artist/create'
    | '/venue/create'
    | '/artist/'
    | '/venue/'
    | '/settings/location'
    | '/settings/my'
    | '/settings/payment'
    | '/venue/accept/$applicationId'
    | '/find/'
    | '/settings/'
    | '/artist/find/'
    | '/artist/my/'
    | '/venue/find/'
    | '/venue/my/'
    | '/application/checkout/$id'
    | '/concert/checkout/$id'
    | '/find/artist/$id'
    | '/find/concert/$id'
    | '/find/venue/$id'
    | '/settings/preferences/create'
    | '/settings/tickets/history'
    | '/settings/tickets/upcoming'
    | '/artist/find/venue/$id'
    | '/venue/find/artist/$id'
    | '/venue/my/applications/$id'
    | '/settings/preferences/'
    | '/settings/tickets/'
    | '/artist/my/concerts/concert/$id'
    | '/venue/my/concerts/concert/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/fail'
    | '/login'
    | '/register'
    | '/stripe-refresh'
    | '/stripe-return'
    | '/success'
    | '/artist/create'
    | '/venue/create'
    | '/'
    | '/artist'
    | '/venue'
    | '/settings/location'
    | '/settings/my'
    | '/settings/payment'
    | '/venue/accept/$applicationId'
    | '/find'
    | '/settings'
    | '/artist/find'
    | '/artist/my'
    | '/venue/find'
    | '/venue/my'
    | '/application/checkout/$id'
    | '/concert/checkout/$id'
    | '/find/artist/$id'
    | '/find/concert/$id'
    | '/find/venue/$id'
    | '/settings/preferences/create'
    | '/settings/tickets/history'
    | '/settings/tickets/upcoming'
    | '/artist/find/venue/$id'
    | '/venue/find/artist/$id'
    | '/venue/my/applications/$id'
    | '/settings/preferences'
    | '/settings/tickets'
    | '/artist/my/concerts/concert/$id'
    | '/venue/my/concerts/concert/$id'
  id:
    | '__root__'
    | '/_customer'
    | '/artist'
    | '/venue'
    | '/fail'
    | '/login'
    | '/register'
    | '/stripe-refresh'
    | '/stripe-return'
    | '/success'
    | '/_customer/settings'
    | '/artist/create'
    | '/venue/create'
    | '/_customer/'
    | '/artist/'
    | '/venue/'
    | '/_customer/settings/location'
    | '/_customer/settings/my'
    | '/_customer/settings/payment'
    | '/venue/accept/$applicationId'
    | '/_customer/find/'
    | '/_customer/settings/'
    | '/artist/find/'
    | '/artist/my/'
    | '/venue/find/'
    | '/venue/my/'
    | '/_customer/application/checkout/$id'
    | '/_customer/concert/checkout/$id'
    | '/_customer/find/artist/$id'
    | '/_customer/find/concert/$id'
    | '/_customer/find/venue/$id'
    | '/_customer/settings/preferences/create'
    | '/_customer/settings/tickets/history'
    | '/_customer/settings/tickets/upcoming'
    | '/artist/find/venue/$id'
    | '/venue/find/artist/$id'
    | '/venue/my/applications/$id'
    | '/_customer/settings/preferences/'
    | '/_customer/settings/tickets/'
    | '/artist/my/concerts/concert/$id'
    | '/venue/my/concerts/concert/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CustomerRouteRoute: typeof CustomerRouteRouteWithChildren
  ArtistRouteRoute: typeof ArtistRouteRouteWithChildren
  VenueRouteRoute: typeof VenueRouteRouteWithChildren
  FailRoute: typeof FailRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StripeRefreshRoute: typeof StripeRefreshRoute
  StripeReturnRoute: typeof StripeReturnRoute
  SuccessRoute: typeof SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stripe-return': {
      id: '/stripe-return'
      path: '/stripe-return'
      fullPath: '/stripe-return'
      preLoaderRoute: typeof StripeReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stripe-refresh': {
      id: '/stripe-refresh'
      path: '/stripe-refresh'
      fullPath: '/stripe-refresh'
      preLoaderRoute: typeof StripeRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fail': {
      id: '/fail'
      path: '/fail'
      fullPath: '/fail'
      preLoaderRoute: typeof FailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue': {
      id: '/venue'
      path: '/venue'
      fullPath: '/venue'
      preLoaderRoute: typeof VenueRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist': {
      id: '/artist'
      path: '/artist'
      fullPath: '/artist'
      preLoaderRoute: typeof ArtistRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_customer': {
      id: '/_customer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CustomerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/': {
      id: '/venue/'
      path: '/'
      fullPath: '/venue/'
      preLoaderRoute: typeof VenueIndexRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/artist/': {
      id: '/artist/'
      path: '/'
      fullPath: '/artist/'
      preLoaderRoute: typeof ArtistIndexRouteImport
      parentRoute: typeof ArtistRouteRoute
    }
    '/_customer/': {
      id: '/_customer/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/venue/create': {
      id: '/venue/create'
      path: '/create'
      fullPath: '/venue/create'
      preLoaderRoute: typeof VenueCreateRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/artist/create': {
      id: '/artist/create'
      path: '/create'
      fullPath: '/artist/create'
      preLoaderRoute: typeof ArtistCreateRouteImport
      parentRoute: typeof ArtistRouteRoute
    }
    '/_customer/settings': {
      id: '/_customer/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof CustomerSettingsRouteRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/venue/my/': {
      id: '/venue/my/'
      path: '/my'
      fullPath: '/venue/my/'
      preLoaderRoute: typeof VenueMyIndexRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/venue/find/': {
      id: '/venue/find/'
      path: '/find'
      fullPath: '/venue/find/'
      preLoaderRoute: typeof VenueFindIndexRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/artist/my/': {
      id: '/artist/my/'
      path: '/my'
      fullPath: '/artist/my/'
      preLoaderRoute: typeof ArtistMyIndexRouteImport
      parentRoute: typeof ArtistRouteRoute
    }
    '/artist/find/': {
      id: '/artist/find/'
      path: '/find'
      fullPath: '/artist/find/'
      preLoaderRoute: typeof ArtistFindIndexRouteImport
      parentRoute: typeof ArtistRouteRoute
    }
    '/_customer/settings/': {
      id: '/_customer/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof CustomerSettingsIndexRouteImport
      parentRoute: typeof CustomerSettingsRouteRoute
    }
    '/_customer/find/': {
      id: '/_customer/find/'
      path: '/find'
      fullPath: '/find/'
      preLoaderRoute: typeof CustomerFindIndexRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/venue/accept/$applicationId': {
      id: '/venue/accept/$applicationId'
      path: '/accept/$applicationId'
      fullPath: '/venue/accept/$applicationId'
      preLoaderRoute: typeof VenueAcceptApplicationIdRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/_customer/settings/payment': {
      id: '/_customer/settings/payment'
      path: '/payment'
      fullPath: '/settings/payment'
      preLoaderRoute: typeof CustomerSettingsPaymentRouteImport
      parentRoute: typeof CustomerSettingsRouteRoute
    }
    '/_customer/settings/my': {
      id: '/_customer/settings/my'
      path: '/my'
      fullPath: '/settings/my'
      preLoaderRoute: typeof CustomerSettingsMyRouteImport
      parentRoute: typeof CustomerSettingsRouteRoute
    }
    '/_customer/settings/location': {
      id: '/_customer/settings/location'
      path: '/location'
      fullPath: '/settings/location'
      preLoaderRoute: typeof CustomerSettingsLocationRouteImport
      parentRoute: typeof CustomerSettingsRouteRoute
    }
    '/_customer/settings/tickets/': {
      id: '/_customer/settings/tickets/'
      path: '/tickets'
      fullPath: '/settings/tickets/'
      preLoaderRoute: typeof CustomerSettingsTicketsIndexRouteImport
      parentRoute: typeof CustomerSettingsRouteRoute
    }
    '/_customer/settings/preferences/': {
      id: '/_customer/settings/preferences/'
      path: '/preferences'
      fullPath: '/settings/preferences/'
      preLoaderRoute: typeof CustomerSettingsPreferencesIndexRouteImport
      parentRoute: typeof CustomerSettingsRouteRoute
    }
    '/venue/my/applications/$id': {
      id: '/venue/my/applications/$id'
      path: '/my/applications/$id'
      fullPath: '/venue/my/applications/$id'
      preLoaderRoute: typeof VenueMyApplicationsIdRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/venue/find/artist/$id': {
      id: '/venue/find/artist/$id'
      path: '/find/artist/$id'
      fullPath: '/venue/find/artist/$id'
      preLoaderRoute: typeof VenueFindArtistIdRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/artist/find/venue/$id': {
      id: '/artist/find/venue/$id'
      path: '/find/venue/$id'
      fullPath: '/artist/find/venue/$id'
      preLoaderRoute: typeof ArtistFindVenueIdRouteImport
      parentRoute: typeof ArtistRouteRoute
    }
    '/_customer/settings/tickets/upcoming': {
      id: '/_customer/settings/tickets/upcoming'
      path: '/tickets/upcoming'
      fullPath: '/settings/tickets/upcoming'
      preLoaderRoute: typeof CustomerSettingsTicketsUpcomingRouteImport
      parentRoute: typeof CustomerSettingsRouteRoute
    }
    '/_customer/settings/tickets/history': {
      id: '/_customer/settings/tickets/history'
      path: '/tickets/history'
      fullPath: '/settings/tickets/history'
      preLoaderRoute: typeof CustomerSettingsTicketsHistoryRouteImport
      parentRoute: typeof CustomerSettingsRouteRoute
    }
    '/_customer/settings/preferences/create': {
      id: '/_customer/settings/preferences/create'
      path: '/preferences/create'
      fullPath: '/settings/preferences/create'
      preLoaderRoute: typeof CustomerSettingsPreferencesCreateRouteImport
      parentRoute: typeof CustomerSettingsRouteRoute
    }
    '/_customer/find/venue/$id': {
      id: '/_customer/find/venue/$id'
      path: '/find/venue/$id'
      fullPath: '/find/venue/$id'
      preLoaderRoute: typeof CustomerFindVenueIdRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/_customer/find/concert/$id': {
      id: '/_customer/find/concert/$id'
      path: '/find/concert/$id'
      fullPath: '/find/concert/$id'
      preLoaderRoute: typeof CustomerFindConcertIdRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/_customer/find/artist/$id': {
      id: '/_customer/find/artist/$id'
      path: '/find/artist/$id'
      fullPath: '/find/artist/$id'
      preLoaderRoute: typeof CustomerFindArtistIdRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/_customer/concert/checkout/$id': {
      id: '/_customer/concert/checkout/$id'
      path: '/concert/checkout/$id'
      fullPath: '/concert/checkout/$id'
      preLoaderRoute: typeof CustomerConcertCheckoutIdRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/_customer/application/checkout/$id': {
      id: '/_customer/application/checkout/$id'
      path: '/application/checkout/$id'
      fullPath: '/application/checkout/$id'
      preLoaderRoute: typeof CustomerApplicationCheckoutIdRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/venue/my/concerts/concert/$id': {
      id: '/venue/my/concerts/concert/$id'
      path: '/my/concerts/concert/$id'
      fullPath: '/venue/my/concerts/concert/$id'
      preLoaderRoute: typeof VenueMyConcertsConcertIdRouteImport
      parentRoute: typeof VenueRouteRoute
    }
    '/artist/my/concerts/concert/$id': {
      id: '/artist/my/concerts/concert/$id'
      path: '/my/concerts/concert/$id'
      fullPath: '/artist/my/concerts/concert/$id'
      preLoaderRoute: typeof ArtistMyConcertsConcertIdRouteImport
      parentRoute: typeof ArtistRouteRoute
    }
  }
}

interface CustomerSettingsRouteRouteChildren {
  CustomerSettingsLocationRoute: typeof CustomerSettingsLocationRoute
  CustomerSettingsMyRoute: typeof CustomerSettingsMyRoute
  CustomerSettingsPaymentRoute: typeof CustomerSettingsPaymentRoute
  CustomerSettingsIndexRoute: typeof CustomerSettingsIndexRoute
  CustomerSettingsPreferencesCreateRoute: typeof CustomerSettingsPreferencesCreateRoute
  CustomerSettingsTicketsHistoryRoute: typeof CustomerSettingsTicketsHistoryRoute
  CustomerSettingsTicketsUpcomingRoute: typeof CustomerSettingsTicketsUpcomingRoute
  CustomerSettingsPreferencesIndexRoute: typeof CustomerSettingsPreferencesIndexRoute
  CustomerSettingsTicketsIndexRoute: typeof CustomerSettingsTicketsIndexRoute
}

const CustomerSettingsRouteRouteChildren: CustomerSettingsRouteRouteChildren = {
  CustomerSettingsLocationRoute: CustomerSettingsLocationRoute,
  CustomerSettingsMyRoute: CustomerSettingsMyRoute,
  CustomerSettingsPaymentRoute: CustomerSettingsPaymentRoute,
  CustomerSettingsIndexRoute: CustomerSettingsIndexRoute,
  CustomerSettingsPreferencesCreateRoute:
    CustomerSettingsPreferencesCreateRoute,
  CustomerSettingsTicketsHistoryRoute: CustomerSettingsTicketsHistoryRoute,
  CustomerSettingsTicketsUpcomingRoute: CustomerSettingsTicketsUpcomingRoute,
  CustomerSettingsPreferencesIndexRoute: CustomerSettingsPreferencesIndexRoute,
  CustomerSettingsTicketsIndexRoute: CustomerSettingsTicketsIndexRoute,
}

const CustomerSettingsRouteRouteWithChildren =
  CustomerSettingsRouteRoute._addFileChildren(
    CustomerSettingsRouteRouteChildren,
  )

interface CustomerRouteRouteChildren {
  CustomerSettingsRouteRoute: typeof CustomerSettingsRouteRouteWithChildren
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerFindIndexRoute: typeof CustomerFindIndexRoute
  CustomerApplicationCheckoutIdRoute: typeof CustomerApplicationCheckoutIdRoute
  CustomerConcertCheckoutIdRoute: typeof CustomerConcertCheckoutIdRoute
  CustomerFindArtistIdRoute: typeof CustomerFindArtistIdRoute
  CustomerFindConcertIdRoute: typeof CustomerFindConcertIdRoute
  CustomerFindVenueIdRoute: typeof CustomerFindVenueIdRoute
}

const CustomerRouteRouteChildren: CustomerRouteRouteChildren = {
  CustomerSettingsRouteRoute: CustomerSettingsRouteRouteWithChildren,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerFindIndexRoute: CustomerFindIndexRoute,
  CustomerApplicationCheckoutIdRoute: CustomerApplicationCheckoutIdRoute,
  CustomerConcertCheckoutIdRoute: CustomerConcertCheckoutIdRoute,
  CustomerFindArtistIdRoute: CustomerFindArtistIdRoute,
  CustomerFindConcertIdRoute: CustomerFindConcertIdRoute,
  CustomerFindVenueIdRoute: CustomerFindVenueIdRoute,
}

const CustomerRouteRouteWithChildren = CustomerRouteRoute._addFileChildren(
  CustomerRouteRouteChildren,
)

interface ArtistRouteRouteChildren {
  ArtistCreateRoute: typeof ArtistCreateRoute
  ArtistIndexRoute: typeof ArtistIndexRoute
  ArtistFindIndexRoute: typeof ArtistFindIndexRoute
  ArtistMyIndexRoute: typeof ArtistMyIndexRoute
  ArtistFindVenueIdRoute: typeof ArtistFindVenueIdRoute
  ArtistMyConcertsConcertIdRoute: typeof ArtistMyConcertsConcertIdRoute
}

const ArtistRouteRouteChildren: ArtistRouteRouteChildren = {
  ArtistCreateRoute: ArtistCreateRoute,
  ArtistIndexRoute: ArtistIndexRoute,
  ArtistFindIndexRoute: ArtistFindIndexRoute,
  ArtistMyIndexRoute: ArtistMyIndexRoute,
  ArtistFindVenueIdRoute: ArtistFindVenueIdRoute,
  ArtistMyConcertsConcertIdRoute: ArtistMyConcertsConcertIdRoute,
}

const ArtistRouteRouteWithChildren = ArtistRouteRoute._addFileChildren(
  ArtistRouteRouteChildren,
)

interface VenueRouteRouteChildren {
  VenueCreateRoute: typeof VenueCreateRoute
  VenueIndexRoute: typeof VenueIndexRoute
  VenueAcceptApplicationIdRoute: typeof VenueAcceptApplicationIdRoute
  VenueFindIndexRoute: typeof VenueFindIndexRoute
  VenueMyIndexRoute: typeof VenueMyIndexRoute
  VenueFindArtistIdRoute: typeof VenueFindArtistIdRoute
  VenueMyApplicationsIdRoute: typeof VenueMyApplicationsIdRoute
  VenueMyConcertsConcertIdRoute: typeof VenueMyConcertsConcertIdRoute
}

const VenueRouteRouteChildren: VenueRouteRouteChildren = {
  VenueCreateRoute: VenueCreateRoute,
  VenueIndexRoute: VenueIndexRoute,
  VenueAcceptApplicationIdRoute: VenueAcceptApplicationIdRoute,
  VenueFindIndexRoute: VenueFindIndexRoute,
  VenueMyIndexRoute: VenueMyIndexRoute,
  VenueFindArtistIdRoute: VenueFindArtistIdRoute,
  VenueMyApplicationsIdRoute: VenueMyApplicationsIdRoute,
  VenueMyConcertsConcertIdRoute: VenueMyConcertsConcertIdRoute,
}

const VenueRouteRouteWithChildren = VenueRouteRoute._addFileChildren(
  VenueRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  CustomerRouteRoute: CustomerRouteRouteWithChildren,
  ArtistRouteRoute: ArtistRouteRouteWithChildren,
  VenueRouteRoute: VenueRouteRouteWithChildren,
  FailRoute: FailRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StripeRefreshRoute: StripeRefreshRoute,
  StripeReturnRoute: StripeReturnRoute,
  SuccessRoute: SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
