// <auto-generated />
using System;
using Concertable.Payment.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Concertable.Payment.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20260428215608_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payment")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Concertable.Payment.Domain.PayoutAccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripeAccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StripeAccountId");

                    b.HasIndex("StripeCustomerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PayoutAccounts", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.StripeEventEntity", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EventProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.ToTable("StripeEvents", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.TransactionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("PaymentIntentId")
                        .IsUnique();

                    b.HasIndex("ToUserId");

                    b.ToTable("Transactions", "payment");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Concertable.Payment.Domain.SettlementTransactionEntity", b =>
                {
                    b.HasBaseType("Concertable.Payment.Domain.TransactionEntity");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.ToTable("SettlementTransactions", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.TicketTransactionEntity", b =>
                {
                    b.HasBaseType("Concertable.Payment.Domain.TransactionEntity");

                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.ToTable("TicketTransactions", "payment");
                });

            modelBuilder.Entity("Concertable.Payment.Domain.SettlementTransactionEntity", b =>
                {
                    b.HasOne("Concertable.Payment.Domain.TransactionEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.Payment.Domain.SettlementTransactionEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.Payment.Domain.TicketTransactionEntity", b =>
                {
                    b.HasOne("Concertable.Payment.Domain.TransactionEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.Payment.Domain.TicketTransactionEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
