/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as StripeReturnRouteImport } from './routes/stripe-return'
import { Route as StripeRefreshRouteImport } from './routes/stripe-refresh'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FailRouteImport } from './routes/fail'
import { Route as ArtistRouteRouteImport } from './routes/artist/route'
import { Route as ArtistIndexRouteImport } from './routes/artist/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ArtistCreateRouteImport } from './routes/artist/create'
import { Route as ArtistMyIndexRouteImport } from './routes/artist/my/index'
import { Route as ArtistFindIndexRouteImport } from './routes/artist/find/index'
import { Route as ArtistOpportunityCheckoutOpportunityIdRouteImport } from './routes/artist/opportunity/checkout.$opportunityId'
import { Route as ArtistFindVenueIdRouteImport } from './routes/artist/find/venue.$id'
import { Route as ArtistApplicationCheckoutApplicationIdRouteImport } from './routes/artist/application/checkout.$applicationId'
import { Route as ArtistMyConcertsConcertIdRouteImport } from './routes/artist/my/concerts/concert.$id'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const StripeReturnRoute = StripeReturnRouteImport.update({
  id: '/stripe-return',
  path: '/stripe-return',
  getParentRoute: () => rootRouteImport,
} as any)
const StripeRefreshRoute = StripeRefreshRouteImport.update({
  id: '/stripe-refresh',
  path: '/stripe-refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FailRoute = FailRouteImport.update({
  id: '/fail',
  path: '/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistRouteRoute = ArtistRouteRouteImport.update({
  id: '/artist',
  path: '/artist',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIndexRoute = ArtistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistCreateRoute = ArtistCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ArtistRouteRoute,
} as any)
const ArtistMyIndexRoute = ArtistMyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => ArtistRouteRoute,
} as any)
const ArtistFindIndexRoute = ArtistFindIndexRouteImport.update({
  id: '/find/',
  path: '/find/',
  getParentRoute: () => ArtistRouteRoute,
} as any)
const ArtistOpportunityCheckoutOpportunityIdRoute =
  ArtistOpportunityCheckoutOpportunityIdRouteImport.update({
    id: '/opportunity/checkout/$opportunityId',
    path: '/opportunity/checkout/$opportunityId',
    getParentRoute: () => ArtistRouteRoute,
  } as any)
const ArtistFindVenueIdRoute = ArtistFindVenueIdRouteImport.update({
  id: '/find/venue/$id',
  path: '/find/venue/$id',
  getParentRoute: () => ArtistRouteRoute,
} as any)
const ArtistApplicationCheckoutApplicationIdRoute =
  ArtistApplicationCheckoutApplicationIdRouteImport.update({
    id: '/application/checkout/$applicationId',
    path: '/application/checkout/$applicationId',
    getParentRoute: () => ArtistRouteRoute,
  } as any)
const ArtistMyConcertsConcertIdRoute =
  ArtistMyConcertsConcertIdRouteImport.update({
    id: '/my/concerts/concert/$id',
    path: '/my/concerts/concert/$id',
    getParentRoute: () => ArtistRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/artist': typeof ArtistRouteRouteWithChildren
  '/fail': typeof FailRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stripe-refresh': typeof StripeRefreshRoute
  '/stripe-return': typeof StripeReturnRoute
  '/success': typeof SuccessRoute
  '/artist/create': typeof ArtistCreateRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/artist/': typeof ArtistIndexRoute
  '/artist/find/': typeof ArtistFindIndexRoute
  '/artist/my/': typeof ArtistMyIndexRoute
  '/artist/application/checkout/$applicationId': typeof ArtistApplicationCheckoutApplicationIdRoute
  '/artist/find/venue/$id': typeof ArtistFindVenueIdRoute
  '/artist/opportunity/checkout/$opportunityId': typeof ArtistOpportunityCheckoutOpportunityIdRoute
  '/artist/my/concerts/concert/$id': typeof ArtistMyConcertsConcertIdRoute
}
export interface FileRoutesByTo {
  '/fail': typeof FailRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stripe-refresh': typeof StripeRefreshRoute
  '/stripe-return': typeof StripeReturnRoute
  '/success': typeof SuccessRoute
  '/artist/create': typeof ArtistCreateRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/artist': typeof ArtistIndexRoute
  '/artist/find': typeof ArtistFindIndexRoute
  '/artist/my': typeof ArtistMyIndexRoute
  '/artist/application/checkout/$applicationId': typeof ArtistApplicationCheckoutApplicationIdRoute
  '/artist/find/venue/$id': typeof ArtistFindVenueIdRoute
  '/artist/opportunity/checkout/$opportunityId': typeof ArtistOpportunityCheckoutOpportunityIdRoute
  '/artist/my/concerts/concert/$id': typeof ArtistMyConcertsConcertIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/artist': typeof ArtistRouteRouteWithChildren
  '/fail': typeof FailRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stripe-refresh': typeof StripeRefreshRoute
  '/stripe-return': typeof StripeReturnRoute
  '/success': typeof SuccessRoute
  '/artist/create': typeof ArtistCreateRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/artist/': typeof ArtistIndexRoute
  '/artist/find/': typeof ArtistFindIndexRoute
  '/artist/my/': typeof ArtistMyIndexRoute
  '/artist/application/checkout/$applicationId': typeof ArtistApplicationCheckoutApplicationIdRoute
  '/artist/find/venue/$id': typeof ArtistFindVenueIdRoute
  '/artist/opportunity/checkout/$opportunityId': typeof ArtistOpportunityCheckoutOpportunityIdRoute
  '/artist/my/concerts/concert/$id': typeof ArtistMyConcertsConcertIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/artist'
    | '/fail'
    | '/login'
    | '/register'
    | '/stripe-refresh'
    | '/stripe-return'
    | '/success'
    | '/artist/create'
    | '/auth/callback'
    | '/artist/'
    | '/artist/find/'
    | '/artist/my/'
    | '/artist/application/checkout/$applicationId'
    | '/artist/find/venue/$id'
    | '/artist/opportunity/checkout/$opportunityId'
    | '/artist/my/concerts/concert/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/fail'
    | '/login'
    | '/register'
    | '/stripe-refresh'
    | '/stripe-return'
    | '/success'
    | '/artist/create'
    | '/auth/callback'
    | '/artist'
    | '/artist/find'
    | '/artist/my'
    | '/artist/application/checkout/$applicationId'
    | '/artist/find/venue/$id'
    | '/artist/opportunity/checkout/$opportunityId'
    | '/artist/my/concerts/concert/$id'
  id:
    | '__root__'
    | '/artist'
    | '/fail'
    | '/login'
    | '/register'
    | '/stripe-refresh'
    | '/stripe-return'
    | '/success'
    | '/artist/create'
    | '/auth/callback'
    | '/artist/'
    | '/artist/find/'
    | '/artist/my/'
    | '/artist/application/checkout/$applicationId'
    | '/artist/find/venue/$id'
    | '/artist/opportunity/checkout/$opportunityId'
    | '/artist/my/concerts/concert/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ArtistRouteRoute: typeof ArtistRouteRouteWithChildren
  FailRoute: typeof FailRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StripeRefreshRoute: typeof StripeRefreshRoute
  StripeReturnRoute: typeof StripeReturnRoute
  SuccessRoute: typeof SuccessRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stripe-return': {
      id: '/stripe-return'
      path: '/stripe-return'
      fullPath: '/stripe-return'
      preLoaderRoute: typeof StripeReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stripe-refresh': {
      id: '/stripe-refresh'
      path: '/stripe-refresh'
      fullPath: '/stripe-refresh'
      preLoaderRoute: typeof StripeRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fail': {
      id: '/fail'
      path: '/fail'
      fullPath: '/fail'
      preLoaderRoute: typeof FailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist': {
      id: '/artist'
      path: '/artist'
      fullPath: '/artist'
      preLoaderRoute: typeof ArtistRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/': {
      id: '/artist/'
      path: '/'
      fullPath: '/artist/'
      preLoaderRoute: typeof ArtistIndexRouteImport
      parentRoute: typeof ArtistRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/create': {
      id: '/artist/create'
      path: '/create'
      fullPath: '/artist/create'
      preLoaderRoute: typeof ArtistCreateRouteImport
      parentRoute: typeof ArtistRouteRoute
    }
    '/artist/my/': {
      id: '/artist/my/'
      path: '/my'
      fullPath: '/artist/my/'
      preLoaderRoute: typeof ArtistMyIndexRouteImport
      parentRoute: typeof ArtistRouteRoute
    }
    '/artist/find/': {
      id: '/artist/find/'
      path: '/find'
      fullPath: '/artist/find/'
      preLoaderRoute: typeof ArtistFindIndexRouteImport
      parentRoute: typeof ArtistRouteRoute
    }
    '/artist/opportunity/checkout/$opportunityId': {
      id: '/artist/opportunity/checkout/$opportunityId'
      path: '/opportunity/checkout/$opportunityId'
      fullPath: '/artist/opportunity/checkout/$opportunityId'
      preLoaderRoute: typeof ArtistOpportunityCheckoutOpportunityIdRouteImport
      parentRoute: typeof ArtistRouteRoute
    }
    '/artist/find/venue/$id': {
      id: '/artist/find/venue/$id'
      path: '/find/venue/$id'
      fullPath: '/artist/find/venue/$id'
      preLoaderRoute: typeof ArtistFindVenueIdRouteImport
      parentRoute: typeof ArtistRouteRoute
    }
    '/artist/application/checkout/$applicationId': {
      id: '/artist/application/checkout/$applicationId'
      path: '/application/checkout/$applicationId'
      fullPath: '/artist/application/checkout/$applicationId'
      preLoaderRoute: typeof ArtistApplicationCheckoutApplicationIdRouteImport
      parentRoute: typeof ArtistRouteRoute
    }
    '/artist/my/concerts/concert/$id': {
      id: '/artist/my/concerts/concert/$id'
      path: '/my/concerts/concert/$id'
      fullPath: '/artist/my/concerts/concert/$id'
      preLoaderRoute: typeof ArtistMyConcertsConcertIdRouteImport
      parentRoute: typeof ArtistRouteRoute
    }
  }
}

interface ArtistRouteRouteChildren {
  ArtistCreateRoute: typeof ArtistCreateRoute
  ArtistIndexRoute: typeof ArtistIndexRoute
  ArtistFindIndexRoute: typeof ArtistFindIndexRoute
  ArtistMyIndexRoute: typeof ArtistMyIndexRoute
  ArtistApplicationCheckoutApplicationIdRoute: typeof ArtistApplicationCheckoutApplicationIdRoute
  ArtistFindVenueIdRoute: typeof ArtistFindVenueIdRoute
  ArtistOpportunityCheckoutOpportunityIdRoute: typeof ArtistOpportunityCheckoutOpportunityIdRoute
  ArtistMyConcertsConcertIdRoute: typeof ArtistMyConcertsConcertIdRoute
}

const ArtistRouteRouteChildren: ArtistRouteRouteChildren = {
  ArtistCreateRoute: ArtistCreateRoute,
  ArtistIndexRoute: ArtistIndexRoute,
  ArtistFindIndexRoute: ArtistFindIndexRoute,
  ArtistMyIndexRoute: ArtistMyIndexRoute,
  ArtistApplicationCheckoutApplicationIdRoute:
    ArtistApplicationCheckoutApplicationIdRoute,
  ArtistFindVenueIdRoute: ArtistFindVenueIdRoute,
  ArtistOpportunityCheckoutOpportunityIdRoute:
    ArtistOpportunityCheckoutOpportunityIdRoute,
  ArtistMyConcertsConcertIdRoute: ArtistMyConcertsConcertIdRoute,
}

const ArtistRouteRouteWithChildren = ArtistRouteRoute._addFileChildren(
  ArtistRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ArtistRouteRoute: ArtistRouteRouteWithChildren,
  FailRoute: FailRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StripeRefreshRoute: StripeRefreshRoute,
  StripeReturnRoute: StripeReturnRoute,
  SuccessRoute: SuccessRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
