global using Concertable.Shared;
global using Concertable.Auth.Domain;
global using Concertable.Authorization.Contracts;
global using Concertable.Identity.Contracts;
global using Concertable.Identity.Domain;
global using Concertable.Concert.Domain;
global using Concertable.Contract.Contracts;
global using Concertable.Contract.Domain;
global using Concertable.Payment.Domain;
